# @package _global_
defaults:
  - override /dataset: cifar10
  - override /model: base

diffusion:
  timesteps: 1000
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
ema:
  enable: true
torch_compile: true
n_epochs: 500
vis_n_samples: 50