# @package _global_
defaults:
  - override /dataset: mnist
  - override /model: tiny

diffusion:
  timesteps: 256
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
ema:
  enable: false
n_epochs: 300
vis_n_samples: 50