# @package _global_
defaults:
  - override /dataset: tiny_imagenet
  - override /model: base

diffusion:
  timesteps: 1000
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
ema:
  enable: true
torch_compile: true
n_epochs: 100
vis_n_samples: 20
batch_size: 64
save_every_epoch: 10
